### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by timbowhite** [masotime/json-url#18]
Hello, thanks for this module.

I get the following error when requiring 'json-url' with node v10.16.3.

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/twhite/foo/node_modules/json-url/dist/node/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Installed with npm v6.13.4. Also got the following warnings running ```npm install json-url```:

```
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> core-js@2.6.11 postinstall /foo/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

**Comment by alexladerman-nav** [comment]
`yarn add @babel/runtime` worked for me

**Comment by outaTiME** [comment]
same here while trying to run in vercel environment, any update ?

**Comment by NikolaiT** [comment]
Same issue here. I don't want to install any `@babel/runtime`, why does this does not work out of the box?
